name: Build APK3
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04  # Versione più vecchia e stabile
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
        
    - name: Install minimal dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip openjdk-8-jdk
        pip3 install buildozer==1.4.0
        
    - name: Set TV mode
      run: sed -i 's/DEVELOPMENT_MODE = True/DEVELOPMENT_MODE = False/' main.py
      
    - name: Create simple keystore
      run: echo -e "\n\n\n\n\n\n\n" | keytool -genkey -v -keystore my-release-key.keystore -alias my-key-alias -keyalg RSA -keysize 2048 -validity 10000 -storepass bibo46 -keypass bibo46
      
    - name: Build
      run: |
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        timeout 30m buildozer android debug || echo "Build timeout or completed"
      
    - name: List files
      run: find . -name "*.apk" -type f
      
    - name: Upload
      if: always()
      run: |
        mkdir -p upload
        find . -name "*.apk" -exec cp {} upload/ \;
        ls -la upload/
        
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: apk-files
        path: upload/