name: Simple APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master, 07-external-telegram-be ]

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Buildozer Action
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        command: buildozer android debug
        buildozer_version: stable
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: telemu-apk
        path: bin/*.apk